### ISSUE TITLE
Node data synchronization error

### ISSUE THREAD

**Issue by wetezos** [ericlee42/metis-verifier-node-setup#10]
I see someone has asked the same questions.  We have use the latest docker-compose.yml ,   and my server have upgraded to 4core 16g memory. Then delete the data ,and  docker-compose up again, but still have this error?

`ERROR[04-14|01:43:50.316] Could not verify                         error="Verifier cannot sync transaction batches to tip: Cannot sync transaction batches to tip: Cannot sync batches: The remote stateroot is not equal to the local: remote %!w(string=0xf28df9dbe2e434ad69a32d5e47de552f8d0472ba8d47dbce1da200fc01f916ad), local %!w(string=0x9d04dbae524e24511d7c9ba1943838c154bb362005588d51f19dc4e54829223c), batch-root %!w(string=0x497d4877548f42f19061012e9c23503a729e247b72b977e11109d9b05554ff70)"
INFO [04-14|01:43:50.807] Syncing transaction batch range          start=13230 end=16529
DEBUG[04-14|01:43:50.807] Fetching transaction batch               index=13230
TRACE[04-14|01:43:50.814] Applying batched transaction             index=954690
TRACE[04-14|01:43:50.814] Applying indexed transaction             index=954690
ERROR[04-14|01:43:50.814] Mismatched transaction                   index=954690`

**Comment by ericlee42** [comment]
duplicate #7
