### ISSUE TITLE
Sync error

### ISSUE THREAD

**Issue by misterpxvg** [ericlee42/metis-verifier-node-setup#11]
Hi guys,

can't find the answer how to resolve:
[04-15|05:46:03.442] Syncing transaction batch range          start=25438 end=25494
l2geth-mainnet_1  | DEBUG[04-15|05:46:03.442] Fetching transaction batch               index=25438
l2geth-mainnet_1  | TRACE[04-15|05:46:03.452] Applying batched transaction             index=2287472
l2geth-mainnet_1  | TRACE[04-15|05:46:03.452] Applying indexed transaction             index=2287472
l2geth-mainnet_1  | ERROR[04-15|05:46:03.452] Mismatched transaction                   index=2287472
l2geth-mainnet_1  | ERROR[04-15|05:46:03.454] Could not verify                         error="Verifier cannot sync transaction batches to tip: Cannot sync transaction batches to tip: Cannot sync batches: The remote stateroot is not equal to the local: remote %!w(string=0xba35d6899c0e97dd0d7be9800300487902d3fdaf24d80001720336f73e7cf79e), local %!w(string=0x494d115314bab29a45139ce34b7faed3b3d8edfd6eb129609bfb9ca38592f119), batch-root %!w(string=0xad590519348392bebdee7640fad69d7a383aaded6b428db2ca509cef2728c5fa)"

Seems it happend apter the the last update.

**Comment by ericlee42** [comment]
Delete your data first

![Screen Shot 2022-04-15 at 14 06 51](https://user-images.githubusercontent.com/92196970/163528639-43ff34c0-5146-48ad-9e5c-0ac3dadffc89.png)

**Comment by jberriman1** [comment]
I'm now getting this error on block 2305470. I have the latest pull from Docker and deleted my data.

**Comment by ericlee42** [comment]
> I'm now getting this error on block 2305470. I have the latest pull from Docker and deleted my data.

Works for us

**Comment by jberriman1** [comment]
I deleted all data from the l2geth image and restarted the container. This forced a rescan of only ETH which fixed the issue so all good now. Thanks
