### ISSUE TITLE
Verifier cannot sync transaction batches to tip

### ISSUE THREAD

**Issue by wetezos** [ericlee42/metis-verifier-node-setup#12]
Hello, we have solved this isusse in the last upgrade. Today, I checked the log and found this error again.

`ERROR[04-22|01:37:24.173] Could not verify                         error="Verifier cannot sync transaction batches to tip: Cannot sync transaction batches to tip: Cannot sync batches: cannot apply batched transaction: Cannot apply batched transaction: Received tx at index 2386325 when looking for 2384945"`

And I see many people block stay in 2384944
<img width="427" alt="image" src="https://user-images.githubusercontent.com/40154568/164580015-593b3443-ee09-4694-9513-bd45c41b2d07.png">

**Comment by ericlee42** [comment]
Did you delete your old data and upgrade your docker images?

**Comment by wetezos** [comment]
> Did you delete your old data and upgrade your docker images?

Sure

**Comment by wetezos** [comment]
I delete my old data and restart node again, the data sync normal now. But I'm a little worried this issue will reappear.

**Comment by ericlee42** [comment]
Did you change volume in compose file?

**Comment by ericlee42** [comment]
Is your image digest same with this?

```
$ docker image ls --digests  | grep metisdao/mvm-andromeda
metisdao/mvm-andromeda    dtl          sha256:d0b7419f7443510a58d073403fc4add4657ba5b58d41e4c89e41bfbff86c571f   878c093d85ca   2 hours ago    912MB
metisdao/mvm-andromeda    l2geth       sha256:39f16ebac9ce7021ad2c098cff544d68be1f739f51251a93f72a74e7e218d36f   18514286d9fe   28 hours ago   41.1MB
```

**Comment by wetezos** [comment]
> Is your image digest same with this?
> 
> ```
> $ docker image ls --digests  | grep metisdao/mvm-andromeda
> metisdao/mvm-andromeda    dtl          sha256:d0b7419f7443510a58d073403fc4add4657ba5b58d41e4c89e41bfbff86c571f   878c093d85ca   2 hours ago    912MB
> metisdao/mvm-andromeda    l2geth       sha256:39f16ebac9ce7021ad2c098cff544d68be1f739f51251a93f72a74e7e218d36f   18514286d9fe   28 hours ago   41.1MB
> ```

Yes
`
docker image ls --digests  | grep metisdao/mvm-andromeda
metisdao/mvm-andromeda       dtl          sha256:d0b7419f7443510a58d073403fc4add4657ba5b58d41e4c89e41bfbff86c571f   878c093d85ca   9 days ago     912MB
metisdao/mvm-andromeda       l2geth       sha256:39f16ebac9ce7021ad2c098cff544d68be1f739f51251a93f72a74e7e218d36f   18514286d9fe   10 days ago    41.1MB
metisdao/mvm-andromeda       <none>       sha256:6f7e62106d47e8e3e24feff5451950b04451d759de5ba3a268427c1427f3e799   0c9da2a5baab   13 days ago    910MB
metisdao/mvm-andromeda       <none>       sha256:cb66c5b23f2d277d0026857a88c40d5f2d67178b721a0c8bc996246c490171bf   6ef693ccd021   3 weeks ago    906MB
metisdao/mvm-andromeda       <none>       sha256:9ba9ab7843876bff8916a249a85c9e15e5fd8d922562a6f5b9a0c98a471e73ac   dfa0b49a0855   2 months ago   43.1MB
metisdao/mvm-andromeda       <none>       sha256:f0b762d9c49b2846ab9956f61c43572008fe0bd8295922353a909f1efa7f87da   1514bc042f17   3 months ago   875MB`

**Comment by wetezos** [comment]
At present, the node is normal. Let's close the issue first. Thanks.
