### ISSUE TITLE
Stuck Block

### ISSUE THREAD

**Issue by jberriman1** [ericlee42/metis-verifier-node-setup#15]
I keep getting stuck on the same block:
l2geth-mainnet_1  | DEBUG[05-15|12:53:43.494] Ancient blocks frozen already            number=2654066 hash=230200…5c9f25 frozen=2564066

I've deleted my l2geth data and restarted however it always get stuck at the same block. The dtl-mainnet seems to be processing transactions. Any idea on how to resolve without having to do a full re-sync ?

**Comment by jberriman1** [comment]
Latest images are being used:

$ docker-compose images
Container                                    Repository                   Tag                 Image Id            Size
metis-verifier-node-setup_dtl-expose_1       ericlee42/metis-dtl-expose   latest              ce5c916b1e3d        10.4MB
metis-verifier-node-setup_dtl-mainnet_1      metisdao/mvm-andromeda       dtl                 878c093d85ca        912MB
metis-verifier-node-setup_l2geth-mainnet_1   metisdao/mvm-andromeda       l2geth              18514286d9fe        41.1MB

**Comment by ericlee42** [comment]
You can try restarting your DTL service and it automatically recovers.

**Comment by jberriman1** [comment]
Unfortunately this did not work. I got the same error when restarting the DTL service (tried multiple combinations). Anything else to try before starting a full re-sync ?

**Comment by jberriman1** [comment]
Seems to have auto corrected itself without me needing to do anything - perhaps the restart did help after some time.
