### ISSUE TITLE
Frozen blocks

### ISSUE THREAD

**Issue by misterpxvg** [ericlee42/metis-verifier-node-setup#16]
Hi Eric,

How can i resolve this without empty the DB ?
![image](https://user-images.githubusercontent.com/34857430/168759914-2c66a3ee-d994-46a7-9354-eaddb8291cc1.png)

**Comment by jberriman1** [comment]
I also hit this issue today.. I emptied the geth db and refreshed but got the issue on the same block.

**Comment by jberriman1** [comment]
I performed a full re-sync and it's ok now.

**Comment by misterpxvg** [comment]
Again frozen block on 3 nodes: index":2759013

**Comment by D5ky** [comment]
I always have to run this commands to fix it, but it is a temporary solution
```
sudo docker-compose rm -fs l2geth-mainnet &&\
sudo rm -rf /data/metis/mainnet/l2geth &&\
sudo docker-compose up -d l2geth-mainnet
```

**Comment by misterpxvg** [comment]
Again frozen block:
l2geth-mainnet_1  | DEBUG[05-31|18:20:53.199] Ancient blocks frozen already            number=2791881 hash=8739b8…c221b1 frozen=2701881

**Comment by ericlee42** [comment]
check out new release https://github.com/ericlee42/metis-verifier-node/releases/tag/20220807
