### ISSUE TITLE
Ok to Modify DATA_TRANSPORT_LAYER__L1_START_HEIGHT ?

### ISSUE THREAD

**Issue by cbrum11** [ericlee42/metis-verifier-node-setup#18]
Noticed `DATA_TRANSPORT_LAYER__L1_START_HEIGHT`.  Can this be set to to a block height that is close to the current block height found at https://etherscan.io/address/0xf209815e595cdf3ed0aaf9665b1772e608ab9380 (to speed up sync) - or is this not suggested for some reason?

**Comment by ericlee42** [comment]
You can do so.

**Comment by cbrum11** [comment]
Interestingly this doesn't work.  If I try to change the block number to ANY block number besides the block number already in the file, `l2geth-mainnet` hangs forever at the log...

```
l2geth-mainnet_1  | DEBUG[06-29|01:37:28.094] Couldn't add port mapping                proto=tcp extport=30303 intport=30303 interface="UPnP or NAT-PMP" err="no UPnP or NAT-PMP router discovered"
```

I even tried deleting `/data/metis`  and resyncing multiple times.  Even let it run over night.  Changing the block number back to the original allows the `l2geth` container to move forward without issue.  I've done this back and forth multiple times with the same result.  Unfortunately - that means a pretty long sync time ;-(
