### ISSUE TITLE
l2geth-mainnet Cannot connect to upstream service

### ISSUE THREAD

**Issue by quan-tanamo** [ericlee42/metis-verifier-node-setup#19]
The dtl-mainnet is operating fine and infura is receiving requests from the docker-compose.yml, main issue is l2geth-mainnet is throwing this error.
[l2geth-error.txt](https://github.com/ericlee42/metis-verifier-node-setup/files/9007154/l2geth-error.txt)

Ubuntu 22.04 is running off a hyper-v VM with bridge network adapter.

**Comment by ericlee42** [comment]
check out new release https://github.com/ericlee42/metis-verifier-node/releases/tag/20220807
