### ISSUE TITLE
Error on "could not verify "

### ISSUE THREAD

**Issue by 3G13** [ericlee42/metis-verifier-node-setup#2]
Hi, 

I am one of the verifier and first of all, would really like to thank all for creating this.

This week, I have encounter twice the error shown below at different index number:
l2geth-mainnet_1  | ERROR[02-26|02:30:11.504] Could not verify                         error="Verifier cannot sync transaction batches to tip: Cannot sync transaction batches to tip: Cannot sync batches: cannot apply batched transaction: Cannot apply batched transaction: Received tx at index 1015330 when looking for 1015090"

Would like to seek for advice on how to avoid having this issue again?
Restarted the node once then it worked fine till the issue appear again later on after 2 days when it sync on higher index number.

Thank you.

**Comment by ericlee42** [comment]
You should use latest compose file

**Comment by 3G13** [comment]
Hi Eric Lee,  
Thank you for the prompt reply. 
I have updated to the latest compose file 10 days ago and it was running fine for close to 3 to 4 days then the error happen. Later I restarted the node, syncing from the beginning and it works fine for another 3 to 4 days and error appeared. 
So, wondering what is the issue with my node. Its not the hardware issue as it is above the requirements. 

Currently, am running replica node and its running fine.
However, would like to check with you on how to submit my txs directly to Metis public rpc node?  

Thank you.

**Comment by ericlee42** [comment]
It's the same with Ethereum.

You can use `eth_sendRawTransaction` RPC method to submit your transaction

**Comment by ericlee42** [comment]
our public rpc endpoint https://docs.metis.io/building-on-metis/connection-details

**Comment by jberriman1** [comment]
I had the same issue. I checked my compose and was missing a setting. I re-configured, deleted all data and re-built and everything works now. Many thanks.

**Comment by jberriman1** [comment]
> I had the same issue. I checked my compose and was missing a setting. I re-configured, deleted all data and re-built and everything works now. Many thanks.

Spoke to soon.. I got the same error. Similar to the above it's ok after a full re-sync but has failed after a few days.

**Comment by 3G13** [comment]
Same here, have to re-sync from start when having the error, then it will sync well for few days.
I try to explore replica node, however unable to work out how "eth_sendRawTransaction" is being submitted. 
Saw that ericlee42 set it as TODO in replica node "Issues", but am unable to help out.

**Comment by ericlee42** [comment]
@3G13 `eth_sendRawTransaction` works now on replica node, check out new compose file

**Comment by jberriman1** [comment]
All - I'm still getting the error "Could not verify error="Verifier cannot sync transaction batches to tip" every few days and need to delete, restart the node and rescan all blocks again to get back into sync. Can I resolve this via a send raw transaction ? If so can someone paste an example command that I can use. Thank you !

**Comment by ericlee42** [comment]
> All - I'm still getting the error "Could not verify error="Verifier cannot sync transaction batches to tip" every few days and need to delete, restart the node and rescan all blocks again to get back into sync. Can I resolve this via a send raw transaction ? If so can someone paste an example command that I can use. Thank you !

as I said before, you should use latest compose file

**Comment by jberriman1** [comment]
Thanks for the prompt response - I've been on the latest compose for a while. Also just double checked - all settings are the same apart from I changed some DB path's and re-mapped some ports. Do I need to run the replica node to ensure I don't see the error ?

**Comment by D5ky** [comment]
I had this issue too. Solved by add more RAM
