### ISSUE TITLE
 After 5 restarts node is still geting stuck on the same transaction - 2762609.

### ISSUE THREAD

**Issue by Axxelius** [ericlee42/metis-verifier-node-setup#20]
Can't solve this problem by using:

docker-compose down
sudo rm -rf /data/metis
docker-compose up -d

Already tried to reinstall all nodes from scratch - same issue.

Any ideas how to fix this?

**Comment by ericlee42** [comment]
We are investigating these problems. Some nodes are running normally and some are not.

**Comment by Axxelius** [comment]
Will this situation influence my reward?

**Comment by ericlee42** [comment]
check out new release https://github.com/ericlee42/metis-verifier-node/releases/tag/20220807
