### ISSUE TITLE
metis-l2geth error "Block sealing ignored"

### ISSUE THREAD

**Issue by BAHRAM1024** [ericlee42/metis-verifier-node-setup#23]
I get this error occasionally and there seems no recovery from that other than resetting the data.

This wastes a lot of time/resources although looks like a recoverable error.

I would like to know more about it and a more efficient way of recovering from there.

Is it possible?

**Comment by ericlee42** [comment]
You can just add `VERBOSITY=3` log level environment variable to l2geth.
