### ISSUE TITLE
Storing Event

### ISSUE THREAD

**Issue by misterpxvg** [ericlee42/metis-verifier-node-setup#24]
Hi all,

one node runned out of storage so we extended the storage. Now the servers respont with msg: Storing Event.
Somebody knows how to fix this ?

Cleared data started all again but every time the server hangs on {"index":475665,[]
![Storing Event](https://user-images.githubusercontent.com/34857430/225092929-423e577f-8e2b-479c-b6a2-16c8a1d8709e.png)

**Comment by ericlee42** [comment]
It's not an error, please share more logs

**Comment by misterpxvg** [comment]
Hi u can close this matter. The server did repeat after 3 reboots.
