### ISSUE TITLE
Sync Error

### ISSUE THREAD

**Issue by jberriman1** [ericlee42/metis-verifier-node-setup#25]
Hi Eric - My node has been stable for several months but just today experienced a sync issue. Is there a way to recover without performing a full re-sync ?

Log from STL is below..

metis-dtl         | {"level":30,"time":1683954974005,"msg":"Service L1_Ingestion_Service is starting..."}
metis-dtl         | {"level":30,"time":1683954974006,"host":"0.0.0.0","port":7878,"msg":"Server started and listening"}
metis-dtl         | {"level":30,"time":1683954974007,"msg":"Service L1_Transport_Server can stop now"}
metis-dtl         | {"level":30,"time":1683954974967,"highestSyncedL1Block":17245799,"targetL1Block":17247799,"msg":"Synchronizing events from Layer 1 (Ethereum)"}
metis-dtl         | {"level":30,"time":1683954977769,"chainId":1088,"parsedEvent":{"index":26480,"target":"0x4200000000000000000000000000000000000007","data":"0xcbd4ece9000000000000000000000000727c6beb46bac2e0418cc1e3f83be1f30ab8056b0000000000000000000000008bab7a91dafbbf3df3219bb115f687edce48ff0e000000000000000000000000000000000000000000000000000000000000008000000000000000000000000000000000000000000000000000000000000067700000000000000000000000000000000000000000000000000000000000000044ed8378f5000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000645e875700000000000000000000000000000000000000000000000000000000","gasLimit":"1900000","origin":"0x192E1101855bD523Ba69a9794e0217f0Db633510","blockNumber":17245800,"timestamp":1683954977,"ctcIndex":null},"msg":"Storing Event:"}
metis-dtl         | {"level":40,"time":1683954977775,"message":"TransactionEnqueued: missing event: TransactionEnqueued","msg":"recovering from a missing event"}
metis-dtl         | Well, that's that. We ran into a fatal error. Here's the dump. Goodbye!
metis-dtl         | (node:1) UnhandledPromiseRejectionWarning: Error: unable to recover from missing event
metis-dtl         |     at L1IngestionService._start (/opt/optimism/packages/data-transport-layer/dist/src/services/l1-ingestion/service.js:161:31)
metis-dtl         |     at async L1IngestionService.start (/opt/optimism/packages/common-ts/dist/base-service.js:35:9)
metis-dtl         |     at async Promise.all (index 1)
metis-dtl         |     at async L1DataTransportService._start (/opt/optimism/packages/data-transport-layer/dist/src/services/main/service.js:64:13)
metis-dtl         |     at async L1DataTransportService.start (/opt/optimism/packages/common-ts/dist/base-service.js:35:9)
metis-dtl         |     at async /opt/optimism/packages/data-transport-layer/dist/src/services/run.js:76:9
metis-dtl         | (Use `node --trace-warnings ...` to show where the warning was created)
metis-dtl         | (node:1) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
metis-dtl         | (node:1) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by ericlee42** [comment]
It's due to ETH outage.

https://www.coindesk.com/tech/2023/05/12/ethereum-resumes-finalizing-blocks-after-second-performance-hiccup-in-24-hours/

I don't have an approach to recover it, you have to resync your node.

**Comment by jberriman1** [comment]
Should I start a re-sync now or wait until you recover?

**Comment by ericlee42** [comment]
No, a typo. I don't have it

**Comment by jberriman1** [comment]
Thanks for the prompt response. I will start a re-sync now.
