### ISSUE TITLE
Stuck node

### ISSUE THREAD

**Issue by jberriman1** [ericlee42/metis-verifier-node-setup#27]
Hi Eric. My node keeps getting stuck every day... I can resolve with a simple restart but things are unstable. Below is an extract from l2geth at the block which gets stuck. Anything I can try to stabilise the node?

metis-l2geth      | TRACE[06-11|12:28:59.212] Deep froze ancient block                 number=6090681 hash=e13abb…b2687a
metis-l2geth      | TRACE[06-11|12:28:59.212] Deep froze ancient block                 number=6090682 hash=851f33…730992
metis-l2geth      | TRACE[06-11|12:28:59.212] Deep froze ancient block                 number=6090683 hash=bd4771…0b25e5
metis-l2geth      | INFO [06-11|12:28:59.267] Deep froze chain segment                 blocks=1072 elapsed=193.833ms number=6090683 hash=bd4771…0b25e5
metis-l2geth      | DEBUG[06-11|12:29:59.268] Ancient blocks frozen already            number=6180684 hash=ab5e2a…1de05c frozen=6090684
metis-l2geth      | DEBUG[06-11|12:30:59.269] Ancient blocks frozen already            number=6180684 hash=ab5e2a…1de05c frozen=6090684
metis-l2geth      | INFO [06-11|12:31:32.189] Syncing transaction batch range          start=35539 end=35539
metis-l2geth      | DEBUG[06-11|12:31:32.189] Fetching transaction batch               index=35539
metis-l2geth      | TRACE[06-11|12:31:32.264] Applying batched transaction             index=6180684
metis-l2geth      | TRACE[06-11|12:31:32.264] Applying indexed transaction             index=6180684
metis-l2geth      | DEBUG[06-11|12:31:32.264] Applying transaction to tip              index=6180684 hash=0xa3a181ae0cb1e7d09fa8a4aa8b0e62d092e7db3b744ce9d6eedbf069321a1531 origin=sequencer
metis-l2geth      | TRACE[06-11|12:31:32.264] Waiting for transaction to be added to chain hash=0xa3a181ae0cb1e7d09fa8a4aa8b0e62d092e7db3b744ce9d6eedbf069321a1531
metis-l2geth      | DEBUG[06-11|12:31:32.264] Attempting to commit rollup transaction  hash=0xa3a181ae0cb1e7d09fa8a4aa8b0e62d092e7db3b744ce9d6eedbf069321a1531
metis-l2geth      | INFO [06-11|12:31:32.264] Use berlin InstructionSet 
metis-l2geth      | DEBUG[06-11|12:31:32.264] Current L1FeeInL2                        fee=0
metis-l2geth      | DEBUG[06-11|12:31:32.264] preCheck                                 checknonce=true gas=248383
metis-l2geth      | DEBUG[06-11|12:31:32.264] buygas                                   gas=248383   initialGas=248383
metis-l2geth      | DEBUG[06-11|12:31:32.264] getting in vm                            gas=225279   value=0                     sender=0xd2c7aB41175155Bae488390914d77ede82f15A60 gasprice=13000000000
metis-l2geth      | INFO [06-11|12:31:32.274] New block                                index=6180684 l1-timestamp=1686482556 l1-blocknumber=17456535 tx-hash=0xa3a181ae0cb1e7d09fa8a4aa8b0e62d092e7db3b744ce9d6eedbf069321a1531 queue-orign=sequencer gas=211322   fees=0.002747186     elapsed=9.943ms
metis-l2geth      | TRACE[06-11|12:31:32.274] Waiting for slot to sign and propagate   delay=0s
metis-l2geth      | DEBUG[06-11|12:31:32.275] Persisted trie from memory database      nodes=98  size=34.99KiB  time=626.912µs   gcnodes=0 gcsize=0.00B gctime=0s livenodes=1 livesize=-2321228.00B
metis-l2geth      | DEBUG[06-11|12:31:32.275] Miner got new head                       height=6180685 block-hash=0x0a93c0bd2866a32f885e7597d5adb6d6b789f34ba12186eb292b9f0424b55011 tx-hash=0xa3a181ae0cb1e7d09fa8a4aa8b0e62d092e7db3b744ce9d6eedbf069321a1531 tx-hash=0xa3a181ae0cb1e7d09fa8a4aa8b0e62d092e7db3b744ce9d6eedbf069321a1531
metis-l2geth      | TRACE[06-11|12:31:32.275] Propagated block                         hash=0a93c0…b55011 recipients=0 duration=2562047h47m16.854s
metis-l2geth      | TRACE[06-11|12:31:32.275] Announced block                          hash=0a93c0…b55011 recipients=0 duration=2562047h47m16.854s
metis-l2geth      | DEBUG[06-11|12:31:32.275] Reinjecting stale transactions           count=0
metis-l2geth      | INFO [06-11|12:31:32.276] Fetch stateroot nil, retry in 1000ms     i=0    index=6180684
metis-l2geth      | INFO [06-11|12:31:33.277] Fetch stateroot nil, retry in 1000ms     i=1    index=6180684
metis-l2geth      | INFO [06-11|12:31:34.280] Fetch stateroot nil, retry in 1000ms     i=2    index=6180684
metis-l2geth      | INFO [06-11|12:31:35.281] Fetch stateroot nil, retry in 1000ms     i=3    index=6180684

As you can see this was paused for several hours until I restarted:

metis-l2geth      | INFO [06-11|22:25:27.841] Fetch stateroot nil, retry in 1000ms     i=35571 index=6180684
metis-l2geth      | INFO [06-11|22:25:28.843] Fetch stateroot nil, retry in 1000ms     i=35572 index=6180684
metis-l2geth      | INFO [06-11|22:25:29.845] Fetch stateroot nil, retry in 1000ms     i=35573 index=6180684

**Comment by ericlee42** [comment]
It's normal.

https://github.com/ericlee42/metis-verifier-node#check-the-services-status
