### ISSUE TITLE
Web server is down

### ISSUE THREAD

**Issue by D5ky** [ericlee42/metis-verifier-node-setup#28]
https://metis-verifier-stats.metissafe.tech/nodes/
Cloudflare Ray ID: 7da2f3186bab0ea7 
<img width="1017" alt="Screenshot 2023-06-20 at 12 22 59" src="https://github.com/ericlee42/metis-verifier-node/assets/15174075/2b7511d4-6c72-4514-8608-5b54bbd5819c">

**Comment by ericlee42** [comment]
it's not maintained by us. and I have asked the team to take a look on it.
