### ISSUE TITLE
NO NETWORK FOUND

### ISSUE THREAD

**Issue by blascokoa** [ericlee42/metis-verifier-node-setup#29]
Facing this error when moved my verifier to a new vps:

metis-dtl  | Well, that's that. We ran into a fatal error. Here's the dump. Goodbye!
metis-dtl  | (node:1) UnhandledPromiseRejectionWarning: Error: could not detect network (event="noNetwork", code=NETWORK_ERROR, version=providers/5.4.4)
metis-dtl  |     at Logger.makeError (/opt/optimism/node_modules/ethers/node_modules/@ethersproject/providers/node_modules/@ethersproject/logger/lib/index.js:199:21)
metis-dtl  |     at Logger.throwError (/opt/optimism/node_modules/ethers/node_modules/@ethersproject/providers/node_modules/@ethersproject/logger/lib/index.js:208:20)
metis-dtl  |     at StaticJsonRpcProvider.<anonymous> (/opt/optimism/node_modules/ethers/node_modules/@ethersproject/providers/lib/json-rpc-provider.js:491:54)
metis-dtl  |     at step (/opt/optimism/node_modules/ethers/node_modules/@ethersproject/providers/lib/json-rpc-provider.js:48:23)
metis-dtl  |     at Object.throw (/opt/optimism/node_modules/ethers/node_modules/@ethersproject/providers/lib/json-rpc-provider.js:29:53)
metis-dtl  |     at rejected (/opt/optimism/node_modules/ethers/node_modules/@ethersproject/providers/lib/json-rpc-provider.js:21:65)
metis-dtl  |     at processTicksAndRejections (internal/process/task_queues.js:95:5)
metis-dtl  | (Use `node --trace-warnings ...` to show where the warning was created)
metis-dtl  | (node:1) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
metis-dtl  | (node:1) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

any idea about how to solve it?

Using ubuntu 20.04

**Comment by ericlee42** [comment]
It's due to your new instance can't connect to your layer1 node.

you need to test the connection first.
