### ISSUE TITLE
How to check whether your node is healthy?

### ISSUE THREAD

**Issue by ericlee42** [ericlee42/metis-verifier-node-setup#3]
Install `curl` and `jq` first, and run following command to check if your node is healthy

```console
$ curl -s 'http://localhost:8080/verifier/get/true/1088'  | jq '.verify.index'
1139855
```

You will get a number, it's current height of your node, and ensure that it is not zero and strictly increasing.

Run following command to check your node is synced

```console
$ curl 'http://localhost:8080/verifier/get/true/1088' | jq '.batch.l1TransactionHash'
"0xef898dfc868d7936bc828513278192305883042c1038e28af3785f9a9770d25a"
```

You will get a transaction hash, it's the latest L1 batch transaction hash.

Open https://etherscan.io/address/0xf209815e595cdf3ed0aaf9665b1772e608ab9380

If the first transaction on the page is equal with you got, your node is synced.

![Screen Shot 2022-03-01 at 2 23 40 PM](https://user-images.githubusercontent.com/92196970/156116269-613a4ecb-affd-4879-ba59-dd15bcbdfa99.png)

**Comment by cbrum11** [comment]
What if you get an older TXH hash?  Should the docker containers be restarted?
