### ISSUE TITLE
Replica vs verifier node

### ISSUE THREAD

**Issue by paymog** [ericlee42/metis-verifier-node-setup#5]
You mention in the readme that we `may not need this` 
https://github.com/ericlee42/metis-verifier-node-setup/blob/bd6021cd752fee1c8dba979ef1051868429e1a84/README.md?plain=1#L3

and that there might be block height lag:

https://github.com/ericlee42/metis-verifier-node-setup/blob/bd6021cd752fee1c8dba979ef1051868429e1a84/README.md?plain=1#L5

What's the correct way of using the mainnet rpc? Can we connect l2geth directly to the mainnet without needing our own verifier or replica? If so, how?

**Comment by ericlee42** [comment]
Yes, you can use our public rpc, and there is a request limit on it ,If your rpc request is very frequent, you should can replica node

**Comment by ericlee42** [comment]
Yes, you can use our public rpc, and there is a request limit on it ,If your rpc request is very frequent, it is recommended to use the replica node
