### ISSUE TITLE
Unable to recover from missing event

### ISSUE THREAD

**Issue by jberriman1** [ericlee42/metis-verifier-node-setup#6]
I'm regularly getting the error below. This triggers after approx 10 days of running but also after any restart of the container. I'm using the latest compose file and other containers are running fine. Memory looks ok (2.7gb used) and no other errors from the host machine. Anything I can try to avoid a missing event error ?

dtl-mainnet_1     | {"level":40,"time":1648424056988,"message":"TransactionEnqueued: missing event: TransactionEnqueued","msg":"recovering from a missing event"}
dtl-mainnet_1     | Well, that's that. We ran into a fatal error. Here's the dump. Goodbye!
dtl-mainnet_1     | (node:1) UnhandledPromiseRejectionWarning: **Error: unable to recover from missing event**
dtl-mainnet_1     |     at L1IngestionService._start (/opt/optimism/packages/data-transport-layer/dist/src/services/l1-ingestion/service.js:157:31)
dtl-mainnet_1     |     at async L1IngestionService.start (/opt/optimism/packages/common-ts/dist/base-service.js:33:9)
dtl-mainnet_1     |     at async Promise.all (index 1)
dtl-mainnet_1     |     at async L1DataTransportService._start (/opt/optimism/packages/data-transport-layer/dist/src/services/main/service.js:64:13)
dtl-mainnet_1     |     at async L1DataTransportService.start (/opt/optimism/packages/common-ts/dist/base-service.js:33:9)
dtl-mainnet_1     |     at async /opt/optimism/packages/data-transport-layer/dist/src/services/run.js:69:9
dtl-mainnet_1     | (Use `node --trace-warnings ...` to show where the warning was created)
dtl-mainnet_1     | (node:1) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
dtl-mainnet_1     | (node:1) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by ericlee42** [comment]
Readme mentions it

**Comment by jberriman1** [comment]
Anyway to recover without doing a full re-sync ? I can't even restart the container without seeing the error
