### ISSUE TITLE
Update Issues

### ISSUE THREAD

**Issue by erduochen** [ericlee42/metis-verifier-node-setup#7]
Hi Team Metis,

After the second update of verifier node based on the latest post, my node stopped working as attached. 
![Untitled](https://user-images.githubusercontent.com/12589356/162838843-5a890061-77c9-4020-b123-96705362b59b.jpg)
![Untitled](https://user-images.githubusercontent.com/12589356/162838905-a5b64914-482a-4fd1-86d9-ac33bb5dadbc.jpg)
I tried to restart but it keeps abnormal. Then I deleted the entire old database, and restarted the service, during the first 5 hours, it is running well and started pulling the data correctly until reaching the block #954690, where the l2geth stopped working again. Please review the screenshot and kindly let me know what's going on for my node. 

Thanks! Oliver

**Comment by erduochen** [comment]
sorry I attached two copies of screenshot.

**Comment by ericlee42** [comment]
What's your hardware spec?

**Comment by erduochen** [comment]
8GB RAM, Core i5, 2TB hard drive, 100MB/s Internet connection

**Comment by erduochen** [comment]
Now I just deleted the database again and restarted the service, for now it's running well, but I am not sure if it can finish all blocks eventually.
![image](https://user-images.githubusercontent.com/12589356/162855890-22146d36-39be-4f45-8120-821fd1fea9b7.png)

**Comment by ericlee42** [comment]
You can try to delete l2geth's data and then restart l2geth to sync from scratch.

FYI

```
docker-compose rm -fs l2geth
rm -rf /data/metis/l2geth
docker-compose up -d l2geth
```

**Comment by erduochen** [comment]
Unfortunately I got stuck at the same block #954690 as shown attached, everything is running perfectly before the second update, but after that, the node stopped working on the same block twice, any suggestion for this issue?
![2022-04-11](https://user-images.githubusercontent.com/12589356/162874985-6fb95359-1d15-449a-83dc-5066a9d3b06c.png)
?

**Comment by islishude** [comment]
Lemme check it out

**Comment by ericlee42** [comment]
Lemme check it out

**Comment by erduochen** [comment]
I got stuck exactly at the same block #954690 the third time, any idea so far?
![2022-04-12](https://user-images.githubusercontent.com/12589356/162970052-080f1bb9-713b-4a93-8675-5e357c334e10.png)

**Comment by ericlee42** [comment]
I deployed a verifier node on a new ec2, I can't reproduce the error.

**Comment by erduochen** [comment]
should I delete all the node code & data and reinstall from the scratch?

**Comment by erduochen** [comment]
more info about this issue, I just reinstalled from scratch, for now the l2geth and dtl services are started up and are syncing the data gradually, but when I run the command **_curl 'http://localhost:8080/verifier/get/true/1088' | jq '.batch.l1TransactionHash'_**,  I found that it can not get the latest L1 batch transaction hash, if you run this command repeatly, you will get different hashes, but none is the most recent one? does this mean the DTL service is not healthy? 

![2022-04-12 (3)](https://user-images.githubusercontent.com/12589356/162997416-899ac9a5-a923-4c4f-9e82-d90c2d3469f5.png)

**Comment by vadimssau** [comment]
I have the same issue

**Comment by ericlee42** [comment]
We have noticed the problem and are actively fixing it

**Comment by Axxelius-Cryptus** [comment]
I have pulled the latest version yesterday evening and restarted the docker. At the beginning everything was fine and today I got this:
<img width="1367" alt="image" src="https://user-images.githubusercontent.com/95581211/163322921-0bad7b1d-93f3-4bee-ba60-3d3544c6fd7e.png">

**Comment by ericlee42** [comment]
It's fixed

https://github.com/ericlee42/metis-verifier-node-setup/releases/tag/20220414
