### ISSUE TITLE
UPGRADE DTL IMAGE

### ISSUE THREAD

**Issue by vadimssau** [ericlee42/metis-verifier-node-setup#8]
After getting the latest "Pull latest DTL image"
image digest 6f7e62106d47
What is different from what is listed on github cb66c5b23f2d
Is it ok?

**Comment by ericlee42** [comment]
> You can get the latest DTL image digest on [docker hub](https://hub.docker.com/r/metisdao/mvm-andromeda/tags?page=1&name=dtl), and make sure that your local image digest is the same as it

**Comment by ericlee42** [comment]
![Screen Shot 2022-04-12 at 17 07 37](https://user-images.githubusercontent.com/92196970/162924269-27ce5704-c219-4a14-a252-40321f8235c9.png)
