### ISSUE TITLE
Node block height is not updated

### ISSUE THREAD

**Issue by wetezos** [ericlee42/metis-verifier-node-setup#9]
I see the node log, which is normal, but the node block height is not updated
`curl -s 'http://localhost:8080/verifier/get/true/1088' | jq '.batch.blockNumber'
13922794`

` docker image inspect metisdao/mvm-andromeda:dtl | jq -r '.[0].RepoDigests[0]' | cut -d ':' -f 2 | cut -c 1-12`
6f7e62106d47

node log
`{"level":30,"time":1649755985798,"highestSyncedL1Block":14569931,"targetL1Block":14569932,"msg":"Synchronizing events from Layer 1 (Ethereum)"}
{"level":30,"time":1649755991221,"highestSyncedL1Block":14569932,"targetL1Block":14569933,"msg":"Synchronizing events from Layer 1 (Ethereum)"}
{"level":30,"time":1649756005642,"highestSyncedL1Block":14569933,"targetL1Block":14569934,"msg":"Synchronizing events from Layer 1 (Ethereum)"}
{"level":30,"time":1649756012784,"highestSyncedL1Block":14569934,"targetL1Block":14569935,"msg":"Synchronizing events from Layer 1 (Ethereum)"}
{"level":30,"time":1649756024584,"highestSyncedL1Block":14569935,"targetL1Block":14569936,"msg":"Synchronizing events from Layer 1 (Ethereum)"}
{"level":30,"time":1649756032355,"highestSyncedL1Block":14569936,"targetL1Block":14569937,"msg":"Synchronizing events from Layer 1 (Ethereum)"}

{"level":30,"time":1649756040906,"highestSyncedL1Block":14569937,"targetL1Block":14569938,"msg":"Synchronizing events from Layer 1 (Ethereum)"}
{"level":30,"time":1649756044763,"chainId":1088,"parsedEvent":{"stateRootBatchEntry":{"index":5879,"blockNumber":14569938,"timestamp":1649755916,"submitter":"0x9cB01d516D930EF49591a05B09e0D33E6286689D","size":85,"root":"0x0f6bd7455bb4150ea9d0aa5ae272c9d59928fc0253c98613c391efcf45b130af","prevTotalElements":2284743,"extraData":"0x000000000000000000000000000000000000000000000000000000006255470c0000000000000000000000009cb01d516d930ef49591a05b09e0d33e6286689d","l1TransactionHash":"0xeeb87aefd665cb86b49ffab02d9955782720a9e782dc3a36a8c2ea3168f665af"},"stateRootEntries":[{"index":2284743,"batchIndex":5879,"value":"0xfd07af36c9edac6f1ccaed41ec78f3f907fc6689c0d3b7d05e5689fced5b229d","confirmed":true},{"index":2284744,"batchIndex":5879,"value":"0x8f81c015f132c09718e309a0a21b212d12b0fc81c156b2e5660b409515022da0","confirmed":true},{"index":2284745,"batchIndex":5879,"value":"0xb3a637c450dc15081e3c1ef3fac6f19110ccab6b1ac4ca0c0e13b22bd4ed99c9","confirmed":true},{"index":2284746,"batchIndex":5879,"value":"0x88c4f7d44924e91d3ce9f3e3b3a291c1fdab8b1b767c6e0c559fc61c7d20191f","confirmed":true},{"index":2284747,"batchIndex":5879,"value":"0xaa2ba72da117073b9283fad6f782d8bcae0493a5eef668a6064b31255e8c6773","confirmed":true},{"index":2284748,"batchIndex":5879,"value":"0xe95ed48225836013d323a006acac5cbaffff79a6572e6ac280c5bc0ef9a4f6ff","confirmed":true},{"index":2284749,"batchIndex":5879,"value":"0x86a1844fbd76614ea598f9040ad2cd7c833b989e4a6126b9c5c59cd6b5d5998a","confirmed":true},{"index":2284750,"batchIndex":5879,"value":"0x2bc3de650c7028a8e2979478f0f080da445aa94e71a232aadf4d56903841f2df","confirmed":true},{"index":2284751,"batchIndex":5879,"value":"0xde39c109fcd67da6e0d47d7153924709d79ee8cacefa159f1dde4fd40628ff3c","confirmed":true},{"index":2284752,"batchIndex":5879,"value":"0x93b07edc9ca70e727100e5d6385474686e02372f9d0abddda42bf298c9183a45","confirmed":true},{"index":2284753,"batchIndex":5879,"value":"0x5c66a151096db3a7b83fd02f0831f112e1dd56164d492ac7632aaf43eb03f0f9","confirmed":true},{"index":2284754,"batchIndex":5879,"value":"0xa7a0b85d3280716f6df7f0fa48d74901e0304688e9df35b6808dff7fb9f3d8ae","confirmed":true},{"index":2284755,"batchIndex":5879,"value":"0xbd6f7bf80b66ed2572abcf2dab7228a58824a2d3156af6754a4a21b93ac142ff","confirmed":true},{"index":2284756,"batchIndex":5879,"value":"0xaa2c746e42d7d0f6a260e63e137f7e08eb9857c54160705a3dd693f8d8ef30ec","confirmed":true},{"index":2284757,"batchIndex":5879,"value":"0x73639fe34ad1be4430bf7929ac9b5064447dab88b752345d3f2bcea4cc04f6b6","confirmed":true},{"index":2284758,"batchIndex":5879,"value":"0xa2119b85e423505e9f54978dfcc11de1db1b578a00d115a460a50aaf53f5050e","confirmed":true},{"index":2284759,"batchIndex":5879,"value":"0x254127f95a8ee31bd2696ba853f2aefb45d95eca6402b1a30669a1a744af2dc3","confirmed":true},{"index":2284760,"batchIndex":5879,"value":"0xef051c93c4f5b1d3d94463585734bc17179d4d9cc73164533e75eb2b2d211e7c","confirmed":true},{"index":2284761,"batchIndex":5879,"value":"0x04e796c470e727aa8dd89f566b9b95bc4adee99a6f7152b0000fc9a42807c24d","confirmed":true},{"index":2284762,"batchIndex":5879,"value":"0x0d8f780b7100d84d85db096273dfdcd94ed2bbe83d784cec3cbd95cdfe9ce864","confirmed":true},{"index":2284763,"batchIndex":5879,"value":"0x8d83483d72e034b9ffd4ef6b217a87db362fa47d575b6ef70145c6badc19eda0","confirmed":true},{"index":2284764,"batchIndex":5879,"value":"0x7f314f8491abd21aa595f333c258014fc6f76a2fb077019aa9e56a73a30e74a5","confirmed":true},{"index":2284765,"batchIndex":5879,"value":"0x4688d48c2b8b79aa9d9ebdfbfef44415fd79803e3fcadd5a727f8f5e2449eecf","confirmed":true},{"index":2284766,"batchIndex":5879,"value":"0x57fbf883f2c120849e87fdc50a819b510331814a8dd6b65d19205cefbe2c7fad","confirmed":true},{"index":2284767,"batchIndex":5879,"value":"0x8a68b48f07f9d4dc52102dea4e87697648ca85467ebd8a9593dad84c7b1cf3b3","confirmed":true},{"index":2284768,"batchIndex":5879,"value":"0x5e68dfe2a4fc15922604583cc51967083eb209e6ba86b636de028a3d82071aae","confirmed":true},{"index":2284769,"batchIndex":5879,"value":"0x3dce2adf430`

**Comment by ericlee42** [comment]
what's the log of l2geth?

**Comment by wetezos** [comment]
> what's the log of l2geth?

I deleted the data and solved the problem after restarting

From this link, my block is a little abnormal.
https://metis-verifier-stats.metissafe.tech/nodes/

{
        "id": 15,
        "ip_address": "65.*.*.149",
        "last_block": 780770
    },

` curl -s 'http://localhost:8080/verifier/get/true/1088' | jq '.batch.blockNumber'
14155096`
